all:
 hosts:
  host1:
  host2:
   ansible_connection: local
 vars:
  ansible__user: ansible
  ansible_ssh_private_key_file: /data/ansible/kee/id_rsa
  #ansible_ssh_pass:
 children:
  mariadb:
   hosts:
    host_bd[1:2]:
